model: 'plainsr'
## parameters for plain
scale: 4
colors: 1
m_plainsr: 16
c_plainsr: 96
with_bn: 1
act_type: 'prelu'
pretrain: null

## parameters for model training
patch_size: 256
batch_size: 32
data_repeat: 64
data_augment: 1

is_qat: 1
epochs: 1000
lr: 0.0005
decays: 250, 500
gamma: 0.5
store_in_ram: 0
log_every: 100
test_every: 1
log_path: "./experiments"
log_name: 

## hardware specification
gpu_ids: 0, 1
threads: 4

## data specification
data_path: '/home/xindongzhang/SR_datasets'