model: 'plainsr'
## parameters for plain
scale: 4
colors: 1
m_plainsr: 4
c_plainsr: 16
with_bn: 0
act_type: 'relu'
pretrain:

## parameters for model training
patch_size: 256
batch_size: 64
data_repeat: 64
data_augment: 1

is_qat: 0
epochs: 50
lr: 0.0005
decays: [100]
gamma: 0.5
log_every: 100
test_every: 1
log_path: "./experiments"
log_name:

## hardware specification
gpu_ids: [0, 1]
threads: 4

## data specification
data_path: '/home/xindongzhang/SR_datasets'
eval_sets: ['Set5', 'Set14', 'B100', 'Urban100', 'Manga109']