model: 'plainsr'
## parameters for plain
scale: 4
colors: 1
m_plainsr: 4
c_plainsr: 16
with_bn: 1
act_type: 'relu'
pretrain:

## parameters for model training
patch_size: 256
batch_size: 32
data_repeat: 64
data_augment: 1

qat_epoch: 100
qat_end: 150
epochs: 200
lr: 0.0005
decays: 100, 200
gamma: 0.1
store_in_ram: 0
log_every: 100
test_every: 1
log_path: "./experiments"
log_name:

## hardware specification
gpu_ids: 0, 1
threads: 8

## data specification
data_path: '/home/xindongzhang/SR_datasets'